package imagesfallback

import "regexp"

var proofBuildPattern = regexp.MustCompile(`c/[^/]*/_`)

var proofCoreChoices = []int{8, 16, 24, 32}

var proofScreenSizes = []int{3000, 4000, 3120, 4160}

var proofNavigatorKeys = []string{
	"registerProtocolHandler−function registerProtocolHandler() { [native code] }",
	"storage−[object StorageManager]",
	"locks−[object LockManager]",
	"appCodeName−Mozilla",
	"permissions−[object Permissions]",
	"share−function share() { [native code] }",
	"webdriver−false",
	"managed−[object NavigatorManagedData]",
	"canShare−function canShare() { [native code] }",
	"vendor−Google Inc.",
	"vendor−Google Inc.",
	"mediaDevices−[object MediaDevices]",
	"vibrate−function vibrate() { [native code] }",
	"storageBuckets−[object StorageBucketManager]",
	"mediaCapabilities−[object MediaCapabilities]",
	"getGamepads−function getGamepads() { [native code] }",
	"bluetooth−[object Bluetooth]",
	"share−function share() { [native code] }",
	"cookieEnabled−true",
	"virtualKeyboard−[object VirtualKeyboard]",
	"product−Gecko",
	"mediaDevices−[object MediaDevices]",
	"canShare−function canShare() { [native code] }",
	"getGamepads−function getGamepads() { [native code] }",
	"product−Gecko",
	"xr−[object XRSystem]",
	"clipboard−[object Clipboard]",
	"storageBuckets−[object StorageBucketManager]",
	"unregisterProtocolHandler−function unregisterProtocolHandler() { [native code] }",
	"productSub−20030107",
	"login−[object NavigatorLogin]",
	"vendorSub−",
	"login−[object NavigatorLogin]",
	"getInstalledRelatedApps−function getInstalledRelatedApps() { [native code] }",
	"mediaDevices−[object MediaDevices]",
	"locks−[object LockManager]",
	"webkitGetUserMedia−function webkitGetUserMedia() { [native code] }",
	"vendor−Google Inc.",
	"xr−[object XRSystem]",
	"mediaDevices−[object MediaDevices]",
	"virtualKeyboard−[object VirtualKeyboard]",
	"virtualKeyboard−[object VirtualKeyboard]",
	"appName−Netscape",
	"storageBuckets−[object StorageBucketManager]",
	"presentation−[object Presentation]",
	"onLine−true",
	"mimeTypes−[object MimeTypeArray]",
	"credentials−[object CredentialsContainer]",
	"presentation−[object Presentation]",
	"getGamepads−function getGamepads() { [native code] }",
	"vendorSub−",
	"virtualKeyboard−[object VirtualKeyboard]",
	"serviceWorker−[object ServiceWorkerContainer]",
	"xr−[object XRSystem]",
	"product−Gecko",
	"keyboard−[object Keyboard]",
	"gpu−[object GPU]",
	"getInstalledRelatedApps−function getInstalledRelatedApps() { [native code] }",
	"webkitPersistentStorage−[object DeprecatedStorageQuota]",
	"doNotTrack",
	"clearAppBadge−function clearAppBadge() { [native code] }",
	"presentation−[object Presentation]",
	"serial−[object Serial]",
	"locks−[object LockManager]",
	"requestMIDIAccess−function requestMIDIAccess() { [native code] }",
	"locks−[object LockManager]",
	"requestMediaKeySystemAccess−function requestMediaKeySystemAccess() { [native code] }",
	"vendor−Google Inc.",
	"pdfViewerEnabled−true",
	"language−zh-CN",
	"setAppBadge−function setAppBadge() { [native code] }",
	"geolocation−[object Geolocation]",
	"userAgentData−[object NavigatorUAData]",
	"mediaCapabilities−[object MediaCapabilities]",
	"requestMIDIAccess−function requestMIDIAccess() { [native code] }",
	"getUserMedia−function getUserMedia() { [native code] }",
	"mediaDevices−[object MediaDevices]",
	"webkitPersistentStorage−[object DeprecatedStorageQuota]",
	"sendBeacon−function sendBeacon() { [native code] }",
	"hardwareConcurrency−32",
	"credentials−[object CredentialsContainer]",
	"storage−[object StorageManager]",
	"cookieEnabled−true",
	"pdfViewerEnabled−true",
	"windowControlsOverlay−[object WindowControlsOverlay]",
	"scheduling−[object Scheduling]",
	"pdfViewerEnabled−true",
	"hardwareConcurrency−32",
	"xr−[object XRSystem]",
	"webdriver−false",
	"getInstalledRelatedApps−function getInstalledRelatedApps() { [native code] }",
	"getInstalledRelatedApps−function getInstalledRelatedApps() { [native code] }",
	"bluetooth−[object Bluetooth]",
}

var proofDocumentKeys = []string{
	"_reactListeningo743lnnpvdg",
	"location",
}

var proofWindowKeys = []string{
	"0",
	"window",
	"self",
	"document",
	"name",
	"location",
	"customElements",
	"history",
	"navigation",
	"locationbar",
	"menubar",
	"personalbar",
	"scrollbars",
	"statusbar",
	"toolbar",
	"status",
	"closed",
	"frames",
	"length",
	"top",
	"opener",
	"parent",
	"frameElement",
	"navigator",
	"origin",
	"external",
	"screen",
	"innerWidth",
	"innerHeight",
	"scrollX",
	"pageXOffset",
	"scrollY",
	"pageYOffset",
	"visualViewport",
	"screenX",
	"screenY",
	"outerWidth",
	"outerHeight",
	"devicePixelRatio",
	"clientInformation",
	"screenLeft",
	"screenTop",
	"styleMedia",
	"onsearch",
	"isSecureContext",
	"trustedTypes",
	"performance",
	"onappinstalled",
	"onbeforeinstallprompt",
	"crypto",
	"indexedDB",
	"sessionStorage",
	"localStorage",
	"onbeforexrselect",
	"onabort",
	"onbeforeinput",
	"onbeforematch",
	"onbeforetoggle",
	"onblur",
	"oncancel",
	"oncanplay",
	"oncanplaythrough",
	"onchange",
	"onclick",
	"onclose",
	"oncontentvisibilityautostatechange",
	"oncontextlost",
	"oncontextmenu",
	"oncontextrestored",
	"oncuechange",
	"ondblclick",
	"ondrag",
	"ondragend",
	"ondragenter",
	"ondragleave",
	"ondragover",
	"ondragstart",
	"ondrop",
	"ondurationchange",
	"onemptied",
	"onended",
	"onerror",
	"onfocus",
	"onformdata",
	"oninput",
	"oninvalid",
	"onkeydown",
	"onkeypress",
	"onkeyup",
	"onload",
	"onloadeddata",
	"onloadedmetadata",
	"onloadstart",
	"onmousedown",
	"onmouseenter",
	"onmouseleave",
	"onmousemove",
	"onmouseout",
	"onmouseover",
	"onmouseup",
	"onmousewheel",
	"onpause",
	"onplay",
	"onplaying",
	"onprogress",
	"onratechange",
	"onreset",
	"onresize",
	"onscroll",
	"onsecuritypolicyviolation",
	"onseeked",
	"onseeking",
	"onselect",
	"onslotchange",
	"onstalled",
	"onsubmit",
	"onsuspend",
	"ontimeupdate",
	"ontoggle",
	"onvolumechange",
	"onwaiting",
	"onwebkitanimationend",
	"onwebkitanimationiteration",
	"onwebkitanimationstart",
	"onwebkittransitionend",
	"onwheel",
	"onauxclick",
	"ongotpointercapture",
	"onlostpointercapture",
	"onpointerdown",
	"onpointermove",
	"onpointerrawupdate",
	"onpointerup",
	"onpointercancel",
	"onpointerover",
	"onpointerout",
	"onpointerenter",
	"onpointerleave",
	"onselectstart",
	"onselectionchange",
	"onanimationend",
	"onanimationiteration",
	"onanimationstart",
	"ontransitionrun",
	"ontransitionstart",
	"ontransitionend",
	"ontransitioncancel",
	"onafterprint",
	"onbeforeprint",
	"onbeforeunload",
	"onhashchange",
	"onlanguagechange",
	"onmessage",
	"onmessageerror",
	"onoffline",
	"ononline",
	"onpagehide",
	"onpageshow",
	"onpopstate",
	"onrejectionhandled",
	"onstorage",
	"onunhandledrejection",
	"onunload",
	"crossOriginIsolated",
	"scheduler",
	"alert",
	"atob",
	"blur",
	"btoa",
	"cancelAnimationFrame",
	"cancelIdleCallback",
	"captureEvents",
	"clearInterval",
	"clearTimeout",
	"close",
	"confirm",
	"createImageBitmap",
	"fetch",
	"find",
	"focus",
	"getComputedStyle",
	"getSelection",
	"matchMedia",
	"moveBy",
	"moveTo",
	"open",
	"postMessage",
	"print",
	"prompt",
	"queueMicrotask",
	"releaseEvents",
	"reportError",
	"requestAnimationFrame",
	"requestIdleCallback",
	"resizeBy",
	"resizeTo",
	"scroll",
	"scrollBy",
	"scrollTo",
	"setInterval",
	"setTimeout",
	"stop",
	"structuredClone",
	"webkitCancelAnimationFrame",
	"webkitRequestAnimationFrame",
	"chrome",
	"caches",
	"cookieStore",
	"ondevicemotion",
	"ondeviceorientation",
	"ondeviceorientationabsolute",
	"launchQueue",
	"documentPictureInPicture",
	"getScreenDetails",
	"queryLocalFonts",
	"showDirectoryPicker",
	"showOpenFilePicker",
	"showSaveFilePicker",
	"originAgentCluster",
	"onpageswap",
	"onpagereveal",
	"credentialless",
	"speechSynthesis",
	"onscrollend",
	"webkitRequestFileSystem",
	"webkitResolveLocalFileSystemURL",
	"sendMsgToSolverCS",
	"webpackChunk_N_E",
	"__next_set_public_path__",
	"next",
	"__NEXT_DATA__",
	"__SSG_MANIFEST_CB",
	"__NEXT_P",
	"_N_E",
	"regeneratorRuntime",
	"__REACT_INTL_CONTEXT__",
	"DD_RUM",
	"_",
	"filterCSS",
	"filterXSS",
	"__SEGMENT_INSPECTOR__",
	"__NEXT_PRELOADREADY",
	"Intercom",
	"__MIDDLEWARE_MATCHERS",
	"__STATSIG_SDK__",
	"__STATSIG_JS_SDK__",
	"__STATSIG_RERENDER_OVERRIDE__",
	"_oaiHandleSessionExpired",
	"__BUILD_MANIFEST",
	"__SSG_MANIFEST",
	"__intercomAssignLocation",
	"__intercomReloadLocation",
}
